---
# tasks_include for keybase_unseal by @bbaassssiiee

- name: initialize Hashicorp Vault
  delegate_to: "{{ groups.vault_instances[0] }}"
  run_once: true
  when: "'{{ check_result.status }}' == '501'"
  no_log: true
  environment:
    VAULT_ADDR: "https://{{ groups.vault_instances[0] }}:{{ vault_port }}"
    VAULT_CACERT: "{{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
  command: |
    vault operator init
      -key-shares={{ key_shares }}
      -key-threshold={{ key_threshold }}
      -format=json
  register: inited
  tags:
    - init

...
